build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: smartctl exporter"
  org.opencontainers.image.description: "Prometheus exporter for SMART disk metrics using smartctl"
  org.opencontainers.image.source: "https://github.com/tigattack/hass-addons"
  org.opencontainers.image.licenses: "Apache-2.0"
